### ISSUE TITLE
Does cairosvg support remote stylesheets?

### ISSUE THREAD

**Issue by foozzi** [Kozea/CairoSVG#376]
for example:
```xml
<?xml-stylesheet type="text/css" href="./style.css"?
```

**Comment by liZe** [comment]
No, it’s not supported.

**Comment by foozzi** [comment]
> No, it’s not supported.

```css
@font-face {
  font-family: 'JetBrains';
  src:  url('/assets/fonts/JetBrains/JetBrains.ttf') format('truetype');
}
g { font-size: 21; font-family: 'JetBrains'; white-space: pre;}
```
font support via @font-face not working too?
