### ISSUE TITLE
embedded fonts are not working

### ISSUE THREAD

**Issue by lrlunin** [Kozea/CairoSVG#390]
Hello,

I generate some pictures in my script using .svg file as a template. I run the script on multiple machines and do not really want to maintain the fonts on all of them and would rather prefer to embed the font into the file.  I did it according to [this instruction](https://inkscape.org/forums/beyond/embed-fonts-in-svg-files/#c26849) (summarized, ttf-> woff2 -> base64 -> css style).

So I have this section in my svg:
```css
<style>
    @font-face { 
    font-family: "Roboto Mono";
    font-weight: normal;
    font-style: normal;
    src: url(data:application/octet-stream;base64,...);
    }
    </style>
```
I checked the rendering of the svg file on the system where none of the used Roboto fonts family is installed. Firefox and Chrome rendered the file correctly using the fonts which were embedded in the file. However, `svg2png` didn't use the fonts and render the files with the default font if Roboto font family is not installed on the system.

The whole file is on the GitHub and can be founded here: https://github.com/lrlunin/pytango-moenchZmqServer/blob/55b3b2c588840aa838cea3dd9217c15f1d7cbdab/scripts/preview_template.svg?short_path=15f8894
